### ISSUE TITLE
resize columns

### ISSUE THREAD

**Issue by veilig2000** [itsgoingd/clockwork-chrome#14]
When looking at the clockwork tab, I'm not able to resize the columns for the (Path,Method,Status,Time)  Most specifically the time columns is cutting off the `ms` string.

**Comment by rowino** [comment]
I'm having an issue with resizing the request column, the last part of the controller function is the most important one. Any update on this issue?

**Comment by itsgoingd** [comment]
Hey, definitively something I want to do, but handling tables with resizing columns is a bit tricky. I might add tooltips for long names as temporary solution instead. I'll try to take a look this week.

**Comment by steveallinson** [comment]
Any progress on this? Tooltips will certainly do the job if resizable columns are too much work.

**Comment by itsgoingd** [comment]
Tooltips and support for resizing columns in the requests table was added in a newly released version 1.5, with bunch of other improvements ([full changelog](https://github.com/itsgoingd/clockwork-chrome/releases/tag/v1.5)).
