### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by mpemberton5** [itsgoingd/clockwork-chrome#16]
Either have the ability to pause traffic or stop the focusing on new entries.

I have background tasks that manage the session and when troubleshooting something from the main call, it loses focus when one of the background events occur.  I hope that makes sense.

Thanks!

**Comment by itsgoingd** [comment]
Hey, I've run into this issue myself pretty often, so definitively something I'd like to add, though I can't promise any ETA.

**Comment by itsgoingd** [comment]
As of newly released version 1.5 clicking on any request other then the last one will pause automatic focusing on new requests, to return to default behaviour you can either click on the last request or clear the requests via clear button or shortcut ([full changelog](https://github.com/itsgoingd/clockwork-chrome/releases/tag/v1.5)).
