### ISSUE TITLE
Add context menu option: Copy url

### ISSUE THREAD

**Issue by sisve** [itsgoingd/clockwork-chrome#17]
I would like to be able to right click a request in the request list and copy the absolute url to the clipboard. The url should include scheme, hostname, port and everything else needed to be able to paste it into the address field of a new tab to navigate to the page (assuming it was a GET request).

**Comment by itsgoingd** [comment]
Clockwork 3.0 now includes an ability to copy the request url in the request tab - [blog post](https://underground.works/blog/clockwork-3.0-now-available) and [full changelog](https://underground.works/clockwork/changelog#content).
