### ISSUE TITLE
Installed on Laravel, not getting info on dev tools

### ISSUE THREAD

**Issue by morfin** [itsgoingd/clockwork-chrome#19]
Hi,

I installed it on Laravel 5.2, follow each step:
1.- Composer installation
2.- Added Provider on app.php
3.- Added middleware
4.- publish config/clockwork.php  (explicitly enabled, enable=>true)

I'm getting headers:

```
X-Clockwork-Id:1458977332.2753.1683523069
X-Clockwork-Version:1.11.1
```

But when I hit a route, I don't see any info on Clockwork tab. 

What else can I check?

Thanks.

**Comment by itsgoingd** [comment]
Hey, what happens when you hit `http://your-site/__clockwork/1458977332.2753.1683523069` in your browser?

**Comment by EventFellows** [comment]
2 thoughts on this:
- in 5.2 there are two arrays to add middleware in app/Http/Kernel.php
-> make sure you add clockwork to $middlewareGroups, not to $routeMiddleware to make it work everywhere

- have you tried to add any data to it. for example 
clock('Message text.');

like explained on the laravel instructrions?
