### ISSUE TITLE
Demands auth option

### ISSUE THREAD

**Issue by xiaohuilam** [itsgoingd/clockwork-chrome#33]
Hello mod,

clockwork is a great debug tool,
but the only thing i want which it was not provided is that clockwork has no option to set a key into header or get argument to make auth.

**Comment by KKSzymanowski** [comment]
I think this belongs here:

https://github.com/itsgoingd/clockwork/issues/new

**Comment by itsgoingd** [comment]
Hey, no concrete plans on this, but it's definitively a good idea and something to consider. I don't want to delay the 2.0 release any longer, but I will take a look at this for some further 2.x version.

**Comment by itsgoingd** [comment]
Clockwork 3.0 now supports simple but extensible authentication - [blog post](https://underground.works/blog/clockwork-3.0-now-available) and [full changelog](https://underground.works/clockwork/changelog#content).
