### ISSUE TITLE
Mouse scroll not working

### ISSUE THREAD

**Issue by KKSzymanowski** [itsgoingd/clockwork-chrome#34]
After updating the extension to the new version the mouse wheel doesn't scroll the Clockwork windows anymore. 

I can still scroll by dragging the scrollbar up and down and by clicking the *up* and *down* arrows on the scrollbar ends, but the wheel does nothing(nor does the two-finger touchpad scrolling). Same thing for the horizontal scrolling, SHIFT+Mouse wheel does nothing.

Environment:
- Google Chrome 61.0.3163.100 64bit
- Clockwork extension 2.0
- Windows 10 Pro 1703 64bit
- Mouse: Logitech M500(highly recommend it)

Also, after updating the composer package from `^1.14` to `^2.0` the **new version** warning didn't disappear:
![image](https://user-images.githubusercontent.com/13980973/31067119-83eb129c-a751-11e7-80c6-ca842e5dd288.png)

**Comment by itsgoingd** [comment]
Hey, just released 2.0.1 with fixes for both issues, can take up to an hour to be published.

Thanks a lot for the report, was a 1px miscalculation in css. :)

**Comment by KKSzymanowski** [comment]
Updated to 2.0.1, works perfectly.
