### ISSUE TITLE
Text search through messages in Log tab

### ISSUE THREAD

**Issue by Gennnji** [itsgoingd/clockwork-chrome#37]
When messages are too much in Log tab, it's difficult to search specific message without removing lots of debug code or adding IFs into the code. Sometimes IFs are also to complicated for getting specific debug info.
Search bar would be great!

**Comment by Gennnji** [comment]
Oh, it seems I didn't match work of search bar at the bottom available by CTRL/CMD + F.
But its strange, I can't find anything almost every time. Maybe it's too slow. One time it filtered by my text phrase, but I didn't get how)

**Comment by itsgoingd** [comment]
We can definitively use some better search/filtering in all tabs, I'll take a look at this for the next release. 👍

**Comment by Gennnji** [comment]
Great! Thank you)

**Comment by spaceemotion** [comment]
Glad to hear that there's an issue for filtering already. I would also love to see a filtering option in the normal requests list, i got quite a few requests on some page loads (tons of avatars) that I'd like to filter out. Cheers!

**Comment by itsgoingd** [comment]
You can now reorder and filter all data tables in Clockwork 3.0 - [blog post](https://underground.works/blog/clockwork-3.0-now-available) and [full changelog](https://underground.works/clockwork/changelog#content).
