### ISSUE TITLE
Visual distinction of Log levels

### ISSUE THREAD

**Issue by Gennnji** [itsgoingd/clockwork-chrome#38]
It's difficult to distinguish by sight messages' levels in Log tab.
For example, warnings and debugs have the same appearance, when warnings could be marked in the log table with badge or icon.

**Comment by itsgoingd** [comment]
Log tab is now more colorful in Clockwork 3.0 - [blog post](https://underground.works/blog/clockwork-3.0-now-available) and [full changelog](https://underground.works/clockwork/changelog#content).
