### ISSUE TITLE
Empty entries on long requests

### ISSUE THREAD

**Issue by spaceemotion** [itsgoingd/clockwork-chrome#40]
On some extra long loading pages the tool only shows an empty entry, with no data whatsoever…

![image](https://user-images.githubusercontent.com/429147/34779428-6fe452f4-f620-11e7-8c00-74240bd8ea83.png)

**Comment by itsgoingd** [comment]
Hey, latest Clockwork 2.1 releases contain some improvements in this area, please let me know if updating fixes some of the issues for you.

**Comment by spaceemotion** [comment]
Hey, thanks for the update! Will do if I can find the time and page this was popping up on :)

**Comment by spaceemotion** [comment]
Closing this as I haven't had any further issues so far.
