### ISSUE TITLE
Clarify new permissions

### ISSUE THREAD

**Issue by tnorthcutt** [itsgoingd/clockwork-chrome#42]
First off: thanks for making this. It's really handy!

I got a popup warning in Chrome today noting that the Clockwork extension required new permissions (access to my browsing history), and it prompted me to accept them or remove the extension.

I did some digging and found that the new permissions are because it's now using the webNavigation API.

Because abuse by Chrome extensions is something that happens, perhaps it would be beneficial to add a security overview note to the README, or a separate SECURITY.md file, explaining what permissions the extension uses, and why.

I'd be happy to help out with that (though I can't answer those two questions currently).

**Comment by itsgoingd** [comment]
Hey, thanks a lot for sharing this important feedback.

While the wording of the warning sounds pretty scary,

- the single thing we use the `webNavigation` for is to know when a user navigates to a new page (eg. clicks a link or enters a url), we don't even care what the url was
- this is used in the new "preserve log" feature so we know when to clear the requests list when user sets "preserve log" to "off"

- we already require the `webRequest` permission which gives us access to read and modify pretty much all HTTP requests made by the browser
- this is used for observing incoming HTTP requests looking for Clockwork headers, we never modify or store the requests and we immediately disregard any HTTP requests once we find they have no Clockwork headers

I think adding a privacy policy section to the readme, Clockwork website and link it in the extension description is the least we can do.

Let me know if you have any further ideas or examples of extensions that handle this well.
