### ISSUE TITLE
Wrong url for request data

### ISSUE THREAD

**Issue by amoseev** [itsgoingd/clockwork-chrome#45]
Hi!

For one page in my application I now see the error "Server returned an invalid JSON.". 
When I update code extension 

```
			try {
				data = JSON.parse(xhr.responseText)
			} catch (e) {
				return callback({ error: 'Server returned an invalid JSON from. Request url: '+ message.url })
			}
```
The message was:
Server returned an invalid JSON. url:http://dev.mydevdomain.ru/__clockwork/#date=2018-03-011519997504-2179-575785715

I suppose the problem in url's with anchor "http://dev.mydevdomain.ru/#date=2018-03-01"

**Comment by itsgoingd** [comment]
Hey, nice find! Fixed this in master, will release a new version over the weekend.

**Comment by amoseev** [comment]
Thanks! All works fine now!
