### ISSUE TITLE
Add support for the current domain

### ISSUE THREAD

**Issue by bigperson** [itsgoingd/clockwork-chrome#59]
I use Chromeiql extension for Google Chrome https://chrome.google.com/webstore/detail/chromeiql/fkkiamalmpiidkljmicmjfbieiclmeij for testing my api, but clockwork not working with domains for which requests are sent

![2018-06-06_18-46-07](https://user-images.githubusercontent.com/4757391/41049690-2baa4bee-69ba-11e8-9b88-493b9fd1bc2a.png)

**Comment by itsgoingd** [comment]
Hey, for Chrome extensions and other apps making requests to your web app, you can use the web UI at http://your-app/__clockowrk.
