### ISSUE TITLE
Database result rows support

### ISSUE THREAD

**Issue by bloep** [itsgoingd/clockwork-chrome#61]
It would be nice, if I can add the result rows to databaseQueries, so I can see the database result in Clockwork.
Same for Firefox extension and WebUI.

**Comment by itsgoingd** [comment]
Hey, this can definitively be useful, my only concern is that this might be *a lot* of additional data collected. I'll consider adding it as an optional feature for the next release.

**Comment by itsgoingd** [comment]
Looked into this and unfortunately I don't see an easy way to get the data from the framework. I'm still considering collecting models events which would include changed attributes, that kinda serves the same purpose. Might revisit for later release if there is more demand for this.
