### ISSUE TITLE
Empty panels in Incognito

### ISSUE THREAD

**Issue by YummyTofu** [itsgoingd/clockwork-chrome#64]
When used in incognito mode, it will sometimes have empty panels or the initial page you opened dev tools on. However, when not in incognito the extension works perfectly fine.

**Comment by itsgoingd** [comment]
Hey, when this happens, can you please try following - while having Clockwork open in one tab open a new tab and type in chrome://inspect, click on "Other" and "inspect" - this will open dev tools window for the Clockwork extension, let me know if there are any errors in the console tab. Thanks!

**Comment by YummyTofu** [comment]
There doesn't appear to be any errors, anything else you want me to debug or try?

**Comment by itsgoingd** [comment]
Hey, can confirm the issue with incognito mode, will be fixed in an update this week.

**Comment by YummyTofu** [comment]
Fixed in 3.0.1
