### ISSUE TITLE
This site requires authentication

### ISSUE THREAD

**Issue by betawax** [itsgoingd/clockwork-chrome#72]
Just installed the latest version of Clockwork, the Web Interface and Firefox Extension is working fine, however the Chrome Extension always gives me a "This site requires authentication." and no data. Please see screenshot attached.

Clockwork Package & Chrome Extension are both v3.1.1.
Chrome version is 70.0.3538.110.

![clockwork](https://user-images.githubusercontent.com/21448/49789854-45ba6800-fd2d-11e8-8f77-d4bb7a93950a.png)

**Comment by betawax** [comment]
It turns out that this happens if the _block third-party cookies_ option is enabled in Chrome settings.

**Comment by itsgoingd** [comment]
Thanks for the report, I can reproduce the issue and will look into this soon.

**Comment by betawax** [comment]
Awesome, thanks!
