### ISSUE TITLE
Database tab: Sorting by Model asc/desc not in proper order

### ISSUE THREAD

**Issue by fitztrev** [itsgoingd/clockwork-chrome#75]
On the Database tab, when clicking the "Model" header to sort, the queries are not sorted alphabetically.

<img width="364" alt="clockwork-model-sort" src="https://user-images.githubusercontent.com/271432/53648262-7663bc80-3c0d-11e9-940d-f53b1bcfe473.png">

Related itsgoingd/clockwork#305

**Comment by itsgoingd** [comment]
Hey, the model column shows short class names by default, but sorts by the fully classified class name that is shown when you click on the short name.

**Comment by fitztrev** [comment]
Ok, thank you.
