### ISSUE TITLE
Visual enhancements

### ISSUE THREAD

**Issue by eugene-manuilov** [itsgoingd/clockwork-chrome#8]
Currently request tab looks a bit messy. All groups are placed too close to each other. It would be better if we could separate groups by adding some margin between them. Something like this:

![clockwork](https://f.cloud.github.com/assets/873049/1512319/7b2aac70-4ac7-11e3-8351-dd68a4f68522.png)

Makes sense?

**Comment by itsgoingd** [comment]
Errors and warnings counts are now displayed in the requests list as of newly released version 1.5.
